name: Lab DevOps


on:  
  push:  
    branches:
      - DevOps
  pull_request:
    branches:
      - DevOps 

jobs:
  build:
    name: Automated building
    runs-on: ubuntu-latest
    container: node:14
    steps:
      - name: Checkout
        uses: actions/checkout@v3   
        
      - name: Install npm package
        run: npm install
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build with Maven
        run: mvn clean package
        
      - name: Run Java application
        run: java -jar /////////////////////  file pom.xml(done) email(searching) 
        
        
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: checking out code
        uses: actions/checkout@v3
          
      - name: raise pr
        uses: peter-evans/create-pull-request@v3
        with:
          branch: "DevOps"
          base: "Develop"
          title: "Automatic pull request"
          committer:  ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>"
          author: ${{ env.GIT_COMMIT_AUTHOR_NAME }} <${{ env.GIT_COMMIT_AUTHOR_EMAIL }}>"
          body:
            This is an automatic pull request 
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-branch: true
          
          
          
      
          
    
    



      
